spring.application.name=fintech
spring.datasource.url=jdbc:postgresql://localhost:5432/fintech


spring.datasource.username = heislerjava
spring.datasource.password = heisler
spring.jpa.hibernate.ddl-auto = update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


twilio.account.sid=AC14942ea07dc3c6e94275bd1779401707
twilio.auth.token=1c9f09c944b4cccd4dfea1c77eea6bd4
twilio.whatsapp.number=whatsapp:+14155238886